- name: update PID.sh
  hosts: all
  gather_facts: true
  become: true
  become_method: sudo
  become_user: zabbix
  
  vars:
  - chmod : 0755
  - owner : zabbix
  - srcsh : /root/PID/PID.sh
  - srcconf : /root/PID/PID.conf
  - destsh : /etc/zabbix/scripts/
  - destconf : /etc/zabbix/zabbix_agent.conf.d/
  
  tasks:
  - debug:
      var: ansible_os_family

  - name: copy PID.sh to Solaris server
    copy:
      src: {{ srcsh }}
      dest: {{ destsh }}
      mode: {{ chmod }}
      owner: {{ owner }}
 
  - name: copy PID.conf to Solaris server
    copy:
      src: {{ srcconf }}
      dest: {{ destconf }}
      mode: {{ chmod }}
      owner: {{ owner }}
 
  - name: restart zabbix-agent
    shell: /etc/init.d/zabbix-agent restart
    when: ansible_os_family == "Solaris"
    
  - name: restart zabbix-agent
    shell: systemctl restart zabbix-agent
    when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"
